import type { Metadata } from "next";
import "./globals.css";
import { cn } from "@/lib/utils";
import Navbar from "@/components/Navbar";
import Sidebar from "@/components/Sidebar";
import { ThemeProvider } from "@/components/Providers/ThemeProvider";
import { Toaster } from "@/components/ui/sonner";
import { fredoka, rubik } from "@/lib/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn("", fredoka.className, rubik.variable)}>
        <Toaster richColors position="bottom-center" />
        <ThemeProvider attribute="class" defaultTheme="dark">
          <div className="flex h-full min-h-svh flex-col">
            <div className="flex-1">
              <Navbar />
              <Sidebar />
              <main className="pt-20 text-muted lg:pl-72">{children}</main>
            </div>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
